/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_org_iitd_socketx_UdpSocketX */

#ifndef _Included_com_org_iitd_socketx_UdpSocketX
#define _Included_com_org_iitd_socketx_UdpSocketX
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_org_iitd_socketx_UdpSocketX
 * Method:    send_udp_packet
 * Signature: (IIIILjava/lang/String;Ljava/lang/String;IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_org_iitd_socketx_UdpSocketX_send_1udp_1packet
  (JNIEnv *, jobject, jint, jint, jint, jint, jstring, jstring, jint, jint, jstring);

/*
 * Class:     com_org_iitd_socketx_UdpSocketX
 * Method:    get_udp_packet
 * Signature: ()Lcom/org/iitd/packetx/UdpPacket;
 */
JNIEXPORT jobject JNICALL Java_com_org_iitd_socketx_UdpSocketX_get_1udp_1packet
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
