/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_org_iitd_socketx_IcmpSocketX */

#ifndef _Included_com_org_iitd_socketx_IcmpSocketX
#define _Included_com_org_iitd_socketx_IcmpSocketX
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_org_iitd_socketx_IcmpSocketX
 * Method:    send_icmp_packet
 * Signature: (IIIILjava/lang/String;Ljava/lang/String;IIIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_org_iitd_socketx_IcmpSocketX_send_1icmp_1packet
  (JNIEnv *, jobject, jint, jint, jint, jint, jstring, jstring, jint, jint, jint, jint, jstring);

/*
 * Class:     com_org_iitd_socketx_IcmpSocketX
 * Method:    get_icmp_packet
 * Signature: ()Lcom/org/iitd/packetx/IcmpPacket;
 */
JNIEXPORT jobject JNICALL Java_com_org_iitd_socketx_IcmpSocketX_get_1icmp_1packet
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
